# Generated by Django 5.1.1 on 2024-10-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='branch',
        ),
    ]
