# Generated by Django 5.1.1 on 2024-10-04 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inventory')),
            ],
            options={
                'verbose_name': 'Inventory Image',
                'verbose_name_plural': 'Inventory Images',
                'db_table': 'inventory_image',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(editable=False)),
                ('status', models.IntegerField(choices=[(1, 'Accepted'), (2, 'Sent'), (3, 'Delivered'), (4, 'Closed')], default=1)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_phone', models.CharField(max_length=15)),
                ('acceptor_name', models.CharField(max_length=255)),
                ('acceptor_phone', models.CharField(max_length=15)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('comment', models.TextField()),
                ('is_paid', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='branch.branch')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_inventories', to='branch.branch')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'db_table': 'inventory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'Accepted'), (2, 'Sent'), (3, 'Delivered'), (4, 'Closed')], default=1)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='inventory.inventory')),
            ],
            options={
                'verbose_name': 'Inventory Action',
                'verbose_name_plural': 'Inventory Actions',
                'db_table': 'inventory_action',
                'ordering': ['action'],
            },
        ),
    ]
