# Generated by Django 5.1.1 on 2024-10-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='acceptor_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sender_phone',
            field=models.CharField(max_length=20),
        ),
    ]
