# Generated by Django 5.1.1 on 2024-10-04 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_truck_number'),
        ('inventory', '0003_alter_inventory_acceptor_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_inventories', to='branch.branch'),
        ),
    ]
