# Generated by Django 5.1.1 on 2024-10-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='number',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
