# Generated by Django 5.1.1 on 2024-10-04 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_driver_branch'),
        ('inventory', '0007_inventoryaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='employees.driver'),
        ),
    ]
