# Generated by Django 5.1.1 on 2024-10-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventory_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryaction',
            name='send_mgs',
            field=models.BooleanField(default=False),
        ),
    ]
