# Generated by Django 5.1.1 on 2024-10-04 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('code', models.PositiveSmallIntegerField(editable=False, unique=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branch',
                'db_table': 'Branch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('number', models.CharField(max_length=8, verbose_name='Number')),
                ('code', models.PositiveSmallIntegerField(editable=False, unique=True, verbose_name='Code')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='branch.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Truck',
                'verbose_name_plural': 'Trucks',
                'db_table': 'Truck',
                'ordering': ['-created_at'],
            },
        ),
    ]
