# Generated by Django 5.1.1 on 2024-10-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.RemoveField(
            model_name='truck',
            name='branch',
        ),
    ]
